version: "3.7"

####################### Services Definition #######################
services:
  client-test:
    image: client:test
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
      target: "test"
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge
