version: "3.7"

####################### Services Definition #######################
services:

  client-test:
    container_name: client_test
    image: client:test
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - default

####################### Networks Definition #######################
networks:
  default:
    driver: bridge
