version: "3.7"

####################### Services Definition #######################
services:
  client-production:
    image: client:production
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
      target: "production"
