name: Continuous Integration

on:
  pull_request:
    branches:
      - development
      - staging
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          docker build --target=ci --tag=client:ci .
          docker run client:ci

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_CLOUD_API_TOKEN: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
      TERRAFORM_CLOUD_ORGANIZATION: ${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}
      TF_WORKSPACE: ${{ github.event.pull_request.base.ref }}
      TF_IN_AUTOMATION: true
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
          cli_config_credentials_hostname: app.terraform.io
          cli_config_credentials_token: TERRAFORM_CLOUD_API_TOKEN

      - name: Format
        id: fmt
        continue-on-error: true
        run: terraform fmt

      - name: Init
        id: init
        run: terraform init -backend-config="organization="${TERRAFORM_CLOUD_ORGANIZATION}""

      - name: Validate
        id: validate
        run: terraform validate

      - name: Plan
        id: plan
        continue-on-error: true
        run: terraform plan -no-color

      - name: Output
        uses: actions/github-script@0.9.0
        with:
          github-token: GITHUB_TOKEN
          script: |
            const output = `#### Terraform Format and Style 🖌 \`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙ \`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖 \`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`${process.env.PLAN}\`\`\`

            </details>`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
