name: Continuous Integration

on:
  pull_request:
    branches:
      - development
      - staging
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          TERRAFORM_CLOUD_API_TOKEN="${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}"
          TERRAFORM_CLOUD_ORGANIZATION="${{ secrets.TERRAFORM_CLOUD_ORGANIZATION }}"
          TF_WORKSPACE="${{ github.event.pull_request.base.ref }}"
          TF_IN_AUTOMATION="true"
          echo ::set-env name=TERRAFORM_CLOUD_API_TOKEN::$TERRAFORM_CLOUD_API_TOKEN
          echo ::set-env name=TERRAFORM_CLOUD_ORGANIZATION::$TERRAFORM_CLOUD_ORGANIZATION
          echo ::set-env name=TF_WORKSPACE::$TF_WORKSPACE
          echo ::set-env name=TF_IN_AUTOMATION::$TF_IN_AUTOMATION

      - name: Test
        run: |
          docker build --target=ci --tag=client:ci .
          docker run client:ci

      - name: Plan
        working-directory: infrastructure
        run: |
          terraform init \
            -input=false \
            -backend-config="token="${TERRAFORM_CLOUD_API_TOKEN}"" \
            -backend-config="organization="${TERRAFORM_CLOUD_ORGANIZATION}""
          terraform plan \
            -input=false
